###########################################
#                                         #
#                  WoLF                   #
#                                         #
#  https://github.com/graiola/wolf-setup  #
#                       .                 #
#                      / V\               #
#                    / `  /               #
#                   <<   |                #
#                   /    |                #
#                 /      |                #
#               /        |                #
#             /    \  \ /                 #
#            (      ) | |                 #
#    ________|   _/_  | |                 #
#  <__________\______)\__)                #
#                                         #
###########################################

version: "3.4"
services:
  wolf-app-bionic:
    container_name: wolf-app:bionic
    build:
      context: .
      dockerfile: ./dockerfiles/wolf/Dockerfile
      args:
        - IMAGE=wolf-base:bionic
    volumes:
      - $HOME/.ssh:$HOME/.ssh
    command: git clone git@github.com:graiola/wolf.git && cd wolf && git submodule update --init && ./setup/debs/debianize.sh
  wolf-app-focal:
    container_name: wolf-app:focal
    build:
      context: .
      dockerfile: ./dockerfiles/wolf/Dockerfile
      args:
        - IMAGE=wolf-base:focal
    volumes:
      - $HOME/.ssh:$HOME/.ssh
    command: git clone git@github.com:graiola/wolf.git && cd wolf && git submodule update --init && ./setup/debs/debianize.sh
