version: "3.4"
services:
  wolf-base-bionic:
    image: wolf-base:bionic
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_PATH}/Dockerfile
      args:
        - IMAGE=nvidia/cudagl:9.2-base-ubuntu18.04
  wolf-base-focal:
    image: wolf-base:focal
    build:
      context: ${CONTEXT_PATH}
      dockerfile: ${DOCKERFILE_PATH}/Dockerfile
      args:
        - IMAGE=nvidia/cudagl:11.4.2-base-ubuntu20.04
