wb_controller:
  ubuntu:
    xenial: ros-kinetic-wb-controller
    bionic: ros-melodic-wb-controller
    focal:  ros-noetic-wb-controller
wolf_gazebo_interface:
  ubuntu:
    xenial: ros-kinetic-wolf-gazebo-interface
    bionic: ros-melodic-wolf-gazebo-interface
    focal:  ros-noetic-wolf-gazebo-interface
wolf_gazebo_resources:
  ubuntu:
    xenial: ros-kinetic-wolf-gazebo-resources
    bionic: ros-melodic-wolf-gazebo-resources
    focal:  ros-noetic-wolf-gazebo-resources
wolf_hardware_interface:
  ubuntu:
    xenial: ros-kinetic-wolf-hardware-interface
    bionic: ros-melodic-wolf-hardware-interface
    focal:  ros-noetic-wolf-hardware-interface
sensors_description:
  ubuntu:
    xenial: ros-kinetic-sensors-description 
    bionic: ros-melodic-sensors-description 
    focal:  ros-noetic-sensors-description
teleop_description:
  ubuntu:
    xenial: ros-kinetic-teleop-description
    bionic: ros-melodic-teleop-description
    focal:  ros-noetic-teleop-description
anymal_description:
  ubuntu:
    xenial: ros-kinetic-anymal-description
    bionic: ros-melodic-anymal-description
    focal:  ros-noetic-anymal-description
anymalc_description:
  ubuntu:
    xenial: ros-kinetic-anymalc-description
    bionic: ros-melodic-anymalc-description
    focal:  ros-noetic-anymalc-description
hyq_description:
  ubuntu:
    xenial: ros-kinetic-hyq-description
    bionic: ros-melodic-hyq-description
    focal:  ros-noetic-hyq-description
aliengo_description:
  ubuntu:
    xenial: ros-kinetic-aliengo-description
    bionic: ros-melodic-aliengo-description
    focal:  ros-noetic-aliengo-description
teleop_description:
  ubuntu:
    xenial: ros-kinetic-teleop-description
    bionic: ros-melodic-teleop-description
    focal:  ros-noetic-teleop-description
spot_description:
  ubuntu:
    xenial: ros-kinetic-spot-description
    bionic: ros-melodic-spot-description
    focal:  ros-noetic-spot-description
solo_description:
  ubuntu:
    xenial: ros-kinetic-solo-description
    bionic: ros-melodic-solo-description
    focal:  ros-noetic-solo-description
kinova_description:
  ubuntu:
    xenial: ros-kinetic-kinova-description
    bionic: ros-melodic-kinova-description
    focal:  ros-noetic-kinova-description
wolf_description_utils:
  ubuntu:
    xenial: ros-kinetic-wolf-description-utils
    bionic: ros-melodic-wolf-description-utils
    focal:  ros-noetic-wolf-description-utils
rt_logger:
  ubuntu:
    xenial: ros-kinetic-rt-logger
    bionic: ros-melodic-rt-logger
    focal:  ros-noetic-rt-logger
